services:
  api:
    build: ./api
    env_file: ./api/.env
    ports:
      - "8080:8080"
    volumes:
      - storage:/botty/storage
    networks:
      - botty
    restart: unless-stopped

  bot:
    build: ./bot
    env_file: ./bot/.env
    depends_on:
      - api
    volumes:
      - storage:/botty/storage
    networks:
      - botty
    restart: unless-stopped

networks:
  botty:

volumes:
  storage:
